---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: listener-80
  namespace: ambassador
spec:
  port: 80
  protocol: HTTP
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL

---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: wildcard
spec:
  hostname: "*" # Выключаем использование https
  acmeProvider:
    authority: none
  requestPolicy:
    insecure:
      action: Route

---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  profile-app
spec:
  prefix: / # Направляем все запросы к profile
  service: profile-app.default

---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  profile-app2
spec:
  prefix: /auth/sign-up # Направляем запрос на регистрацию нового пользователя на profile сервис
  rewrite: /sign-up
  service: profile-app.default


---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  auth-app
spec:
  prefix: /auth/ # Направляем запросы c префиксом /auth к auth-service для логина и логаута
  service: auth-app.default
  bypass_auth: true # Отключаем аутентификацию на запросы к auth-service

---
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: auth-app
spec:
  External:
    auth_service: "auth-app.default"
    path_prefix: "/session/cookie"
    allowed_authorization_headers:
      - "x-username"
      - "x-auth-token"

---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: auth-check
spec:
  rules:
    - host: "*"
      path: "/auth*" # Разрешаем доступ к /auth всем запросам
      filters: []
    - host: "*"
      path: "*"
      filters:
        - name: "auth-app"  # Применяем auth-service фильтр к ресурсам

---
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: jwt-auth
spec:
  JWT: # Создаем фильтр для проверки JWT токена
    jwksURI: "http://auth-app.default.svc.cluster.local/.well-known/jwks.json"
    issuer: "http://auth-app"
    injectRequestHeaders:
      - name: "x-auth-token"
        value: "{{ .token.Raw }}"

---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: auth-check # Подменяем старые правила, потому что есть подозрения, что ambassador их не мержит
spec:
  rules: # Применяем jwt фильтр к ресурсам
    - host: "*"
      path: "/auth*" # Разрешаем доступ к /auth всем запросам
      filters: null
    - host: "*"
      path: "*" # Запрещаем доступ к остальным ресурсам для запросов без JWT
      filters:
        - name: "auth-app"
        - name: "jwt-auth"
