apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
spec:
  replicas: {{ .Values.auth.replicaCount}}
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
      - name: auth-app
        image: {{ .Values.auth.container.image}}
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
        envFrom:
          - configMapRef:
              name: auth-app-config
          - secretRef:
              name: auth-redis-secret