apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-app-config
data:
  APP_PORT: "8080"
  APP_SERVICE_NAME: "profile"
  LOG_LEVEL: "debug"
  DB_POOLMAX: "10"
  DB_TIMEOUT: "1"
  TOKEN_PUBLIC_KEY_URI: "http://auth-app.default.svc.cluster.local/.well-known/jwks.json"