apiVersion: v1
kind: Secret
metadata:
  name: profile-postgres-secret
type: Opaque
stringData:
  DB_HOST: app-profiledb
  DB_DRIVER: postgres
  DB_USER: {{ .Values.profiledb.auth.username }}
  DB_PASSWORD: {{ .Values.profiledb.auth.password }}
  DB_NAME: {{ .Values.profiledb.auth.database }}
  DB_PORT: "5432"